### ISSUE TITLE
4.26 support

### ISSUE THREAD

**Issue by SavannahGames** [nutti/UE4-Noise-BlueprintLibrary#2]
Hi, would it be possible for you to add 4.26 support? It does not seem to work on 4.26.

**Comment by nutti** [comment]
@SavannahGames 

Could you tell me the problems on 4.26?
It would help me to fix the issue.

**Comment by SavannahGames** [comment]
> @SavannahGames
> 
> Could you tell me the problems on 4.26?
> It would help me to fix the issue.



"ProjectName could not be compiled. Try rebuilding from source manually".  I have tried to regenerate visual studio project files many times, still this issue comes up. 

  C:/Users/Admin/Desktop/UnrealEngine4/NoiseBlueprint/Plugins/NoiseBlueprintLibrary/Source/NoiseBlueprintLibrary/Private/PerlinNoise/PerlinNoiseBPLibrary.cpp(1): fatal error C1083: Cannot open include file: 'PerlinNoiseBPLibrary.h': No such file or directory -- this also comes up, even when I put the header file there, it says suppressed.lib & refuses to compile, says "critical error"

maybe I unzipped them wrong but i dont think so, if i did any mistake let me know! would love to get this working. 
Project name is "NoiseBlueprint", freshly made project and selected c++

**Comment by nutti** [comment]
@SavannahGames 

Thanks!
I will check it.

**Comment by SavannahGames** [comment]
> @SavannahGames
> 
> Thanks!
> I will check it.
Just wanted to let you know that I tested it on 4.22 and it works flawlessly. 4.26 does not want to seem to work at all. so 4.26 definitely needs some repairing or rewriting of code.

**Comment by nutti** [comment]
This error is now resolved by using master branch's source codes.

Thanks for your report @SavannahGames !
